version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mappe le port hôte au conteneur
    volumes:
      - .:/index # Monte le répertoire actuel dans le conteneur pour le développement
      - /app/node_modules # Exclut les node_modules pour éviter les conflits
    environment:
      NODE_ENV: development # Ajoute des variables d'environnement si nécessaire