# Étape 1 : Utiliser une image de base officielle Node.js
FROM node:16-alpine

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste des fichiers de l'application
COPY . .

# Étape 6 : Exposer le port utilisé par l'application
EXPOSE 3000

# Étape 7 : Définir la commande de démarrage
CMD ["npx", "nodemon", "app.js"]
